services: 

  core:
    build:
      context: ./core
    container_name: core
    ports:
      - 8000:8000
    volumes:
      - ./core:/core
    working_dir: /core
    # command: python manage.py runserver 0:8000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - apiservice

networks:
  apiservice:

volumes:
  pgdata:
